import 'dart:isolate';

import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:dart2tinygo/src/frontend/bindings.dart';

/// The result of converting a checked entry point to Go source, per
/// `HANDOFF_dart2tinygo.md` §4.2/§4.4: no `fmt.Sprintf`, string
/// interpolation is concatenated with `strconv` based on type.
///
/// Callers must have already run [checkEntryPoint] and confirmed there are
/// no [UnsupportedSyntaxError]s; this generator assumes the AST matches the
/// v0.1 minimal subset and does not re-validate it.
class GeneratedGoFile {
  GeneratedGoFile(this.source, {this.localModules = const []});

  final String source;

  /// Binding Go modules that live next to their Dart package (see
  /// `GoImportSpec.localModule`). The CLI turns each into a `require` +
  /// `replace` pair in the generated `go.mod` so the output builds from a
  /// checkout without publishing anything.
  final List<GoLocalModule> localModules;
}

/// Everything the generated file needs from outside itself, collected while
/// walking `main()`.
class GoDeps {
  GoDeps({this.dartrtModule});

  /// Go imports keyed by import path. The value is the alias (`null` for
  /// stdlib packages and for bindings that rely on the package's own name).
  final imports = <String, String?>{};

  /// Binding modules with an in-tree Go runtime, keyed by module path so a
  /// binding used many times is required once.
  final localModules = <String, GoLocalModule>{};

  /// The core's own `dartrt` runtime (`packages/dart2tinygo/go/`, see
  /// `docs/mapping.md` "Common Go runtime"), resolved once up front so the
  /// rest of the tree walk stays synchronous. `null` only if this checkout
  /// is missing `packages/dart2tinygo/go/` — a packaging bug, not something
  /// a Dart entry point can trigger.
  final GoLocalModule? dartrtModule;

  /// Counter behind the synthetic `_t0`, `_t1`, ... receiver names a cascade
  /// used as a statement mints (`docs/mapping.md`, "Cascades and method
  /// chaining") — monotonically increasing across the whole file keeps every
  /// temp unique regardless of which function it's minted in.
  int nextTempId = 0;

  /// Set while writing a class's constructor/method body (#32), so a field
  /// reference — implicit `this` (`value`) or explicit (`this.value`) —
  /// knows which Go receiver variable to qualify itself with. `null`
  /// everywhere else (top-level functions have no receiver). Read by
  /// [_writeFieldAccess]; set/cleared around each body by
  /// [_writeConstructor]/[_writeMethodDeclaration], the same way `deps`
  /// itself is threaded through the whole tree walk rather than as a
  /// function parameter, since generation is single-threaded and strictly
  /// nested.
  MethodScope? methodScope;
}

/// See [GoDeps.methodScope].
class MethodScope {
  MethodScope(this.receiver);

  /// The Go receiver variable name (`docs/mapping.md`: the class's own name,
  /// first letter lowercased — `Counter` → `c`).
  final String receiver;
}

/// Converts every top-level function and enum of a checked
/// [ResolvedUnitResult] (`main()` plus any others — see `docs/mapping.md`,
/// "Top-level functions", "enum") into a single-file Go program, in source
/// order (Go doesn't care about declaration order, so this is purely for a
/// readable diff against the Dart source).
Future<GeneratedGoFile> generateGoFile(ResolvedUnitResult result) async {
  final deps = GoDeps(dartrtModule: await _resolveDartrtModule());
  final imports = deps.imports;
  final funcsBuffer = StringBuffer();
  for (final declaration in result.unit.declarations) {
    if (declaration is FunctionDeclaration) {
      _writeFunctionDeclaration(declaration, funcsBuffer, deps);
    } else if (declaration is EnumDeclaration) {
      _writeEnumDeclaration(declaration, funcsBuffer, deps);
    } else if (declaration is ClassDeclaration) {
      _writeClassDeclaration(declaration, funcsBuffer, deps);
    }
  }

  final out = StringBuffer()
    ..writeln('// Code generated by dart2tinygo. DO NOT EDIT.')
    ..writeln('package main')
    ..writeln();
  if (imports.isNotEmpty) {
    final sorted = imports.keys.toList()..sort();
    String spec(String path) {
      final alias = imports[path];
      return alias == null ? '"$path"' : '$alias "$path"';
    }

    if (sorted.length == 1) {
      out.writeln('import ${spec(sorted.single)}');
    } else {
      out.writeln('import (');
      for (final import in sorted) {
        out.writeln('\t${spec(import)}');
      }
      out.writeln(')');
    }
    out.writeln();
  }
  out.write(funcsBuffer);

  return GeneratedGoFile(
    out.toString(),
    localModules: deps.localModules.values.toList(),
  );
}

/// `T name(...) { ... }` (or `T name(...) => expr;`) maps 1:1 onto Go's
/// `func name(...) T { ... }` — including `main()`, which is simply the
/// case with no parameters and a `void` return. Parameters are always
/// simple positional ones by the time the checker has accepted this
/// declaration (`_checkFunctionDeclaration`).
void _writeFunctionDeclaration(
  FunctionDeclaration declaration,
  StringBuffer out,
  GoDeps deps,
) {
  final parameters = declaration.functionExpression.parameters?.parameters ??
      const <FormalParameter>[];
  final paramGo = parameters
      .cast<SimpleFormalParameter>()
      .map((p) =>
          '${p.name!.lexeme} ${_goTypeName(p.declaredFragment!.element.type, deps)}')
      .join(', ');

  final returnType = declaration.returnType?.type;
  final isVoidReturn = returnType == null || returnType is VoidType;
  final returnGo = isVoidReturn ? '' : ' ${_goTypeName(returnType, deps)}';

  out.writeln('func ${declaration.name.lexeme}($paramGo)$returnGo {');
  final body = declaration.functionExpression.body;
  if (body is BlockFunctionBody) {
    for (final statement in body.block.statements) {
      _writeStatement(statement, out, deps, indent: '\t');
    }
  } else if (body is ExpressionFunctionBody) {
    if (isVoidReturn) {
      // `void f() => expr;`: `expr` on its own, no `return` (Go rejects
      // `return <value>` in a function with no declared return type).
      _writeExpressionStatement(body.expression, out, deps, indent: '\t');
    } else {
      out.writeln('\treturn ${_writeExpression(body.expression, deps)}');
    }
  }
  out.writeln('}');
  out.writeln();
}

/// `enum Mode { off, on }` (#31, `docs/mapping.md`): `type Mode int` +
/// `const ( ModeOff Mode = iota; ModeOn )` + a name table indexed by the
/// value itself (Go allows indexing with any type whose underlying type is
/// an integer type, the same way `time.Month.String()` indexes into its own
/// name table in the Go standard library — no cast needed). A `@GoType`
/// enum (a binding enum, e.g. `Pin`) emits nothing here: like any other
/// binding, its constants only ever reference an existing Go identifier via
/// `@GoName` (see [_writeEnumConstantReference]), so there is no Go
/// declaration for *this* generator to own.
void _writeEnumDeclaration(
  EnumDeclaration declaration,
  StringBuffer out,
  GoDeps deps,
) {
  final element = declaration.declaredFragment!.element;
  if (goTypeOf(element) != null) return;

  final name = element.name!;
  final constants = declaration.body.constants;

  out.writeln('type $name int');
  out.writeln();
  out.writeln('const (');
  for (var i = 0; i < constants.length; i++) {
    final constName = '$name${_capitalize(constants[i].name.lexeme)}';
    out.writeln(i == 0 ? '\t$constName $name = iota' : '\t$constName');
  }
  out.writeln(')');
  out.writeln();

  final namesVar = '${_lowerFirst(name)}Names';
  final values =
      constants.map((c) => _goStringLiteral(c.name.lexeme)).join(', ');
  out.writeln('var $namesVar = [...]string{$values}');
  out.writeln();
}

String _capitalize(String s) =>
    s.isEmpty ? s : '${s[0].toUpperCase()}${s.substring(1)}';

String _lowerFirst(String s) =>
    s.isEmpty ? s : '${s[0].toLowerCase()}${s.substring(1)}';

/// `class Foo { ... }` (#32, `docs/mapping.md` "class (no inheritance)"):
/// `type Foo struct { ... }` (one field per `FieldDeclaration` variable, in
/// declaration order) + `func NewFoo(...) *Foo { ... }` + one pointer-
/// receiver method per `MethodDeclaration`. The checker
/// (`_checkClassDeclaration`) has already confirmed exactly one plain
/// generative constructor and only plain instance fields/methods, so this
/// only needs to walk `declaration.body.members` and emit each kind.
void _writeClassDeclaration(
  ClassDeclaration declaration,
  StringBuffer out,
  GoDeps deps,
) {
  final name = declaration.declaredFragment!.element.name!;

  out.writeln('type $name struct {');
  for (final member in declaration.body.members) {
    if (member is! FieldDeclaration) continue;
    for (final variable in member.fields.variables) {
      final type = variable.declaredFragment!.element.type;
      out.writeln('\t${variable.name.lexeme} ${_goTypeName(type, deps)}');
    }
  }
  out.writeln('}');
  out.writeln();

  final constructor =
      declaration.body.members.whereType<ConstructorDeclaration>().first;
  _writeConstructor(name, constructor, out, deps);

  for (final member in declaration.body.members) {
    if (member is MethodDeclaration) {
      _writeMethodDeclaration(name, member, out, deps);
    }
  }
}

/// The Go receiver variable name for a class named [className]: its own
/// first letter, lowercased (`Counter` → `c`, `docs/mapping.md`).
String _receiverName(String className) =>
    className.substring(0, 1).toLowerCase();

/// `Foo(<params>) { ... }` (a class's single generative constructor, #32):
/// each `this.field` parameter becomes a struct-literal field; any
/// remaining body statements run afterward with the receiver already
/// holding those fields, the same way a method body does
/// ([_writeMethodDeclaration]). A trivial constructor (`this.x` parameters
/// only, no body) skips the intermediate receiver local entirely and
/// returns the struct literal directly, matching the shape a human would
/// write by hand.
void _writeConstructor(
  String className,
  ConstructorDeclaration constructor,
  StringBuffer out,
  GoDeps deps,
) {
  final parameters = constructor.parameters.parameters;
  final paramGo = parameters.map((parameter) {
    if (parameter is FieldFormalParameter) {
      final element = parameter.declaredFragment!.element;
      return '${parameter.name.lexeme} ${_goTypeName(element.type, deps)}';
    }
    final simple = parameter as SimpleFormalParameter;
    return '${simple.name!.lexeme} '
        '${_goTypeName(simple.declaredFragment!.element.type, deps)}';
  }).join(', ');

  final fieldInits = parameters
      .whereType<FieldFormalParameter>()
      .map((p) => '${p.name.lexeme}: ${p.name.lexeme}')
      .join(', ');

  final body = constructor.body;
  final statements =
      body is BlockFunctionBody ? body.block.statements : const <Statement>[];

  out.writeln('func New$className($paramGo) *$className {');
  if (statements.isEmpty) {
    out.writeln('\treturn &$className{$fieldInits}');
  } else {
    final receiver = _receiverName(className);
    out.writeln('\t$receiver := &$className{$fieldInits}');
    deps.methodScope = MethodScope(receiver);
    for (final statement in statements) {
      _writeStatement(statement, out, deps, indent: '\t');
    }
    deps.methodScope = null;
    out.writeln('\treturn $receiver');
  }
  out.writeln('}');
  out.writeln();
}

/// A pointer-receiver instance method (#32): `func (c *Foo) name(...) T {
/// ... }`, identical in shape to a top-level function
/// ([_writeFunctionDeclaration]) plus the receiver clause. The body is
/// written with [GoDeps.methodScope] set so a field reference inside it
/// resolves to `<receiver>.<field>` ([_writeFieldAccess]).
void _writeMethodDeclaration(
  String className,
  MethodDeclaration method,
  StringBuffer out,
  GoDeps deps,
) {
  final receiver = _receiverName(className);
  final parameters = method.parameters?.parameters ?? const <FormalParameter>[];
  final paramGo = parameters
      .cast<SimpleFormalParameter>()
      .map((p) =>
          '${p.name!.lexeme} ${_goTypeName(p.declaredFragment!.element.type, deps)}')
      .join(', ');

  final returnType = method.returnType?.type;
  final isVoidReturn = returnType == null || returnType is VoidType;
  final returnGo = isVoidReturn ? '' : ' ${_goTypeName(returnType, deps)}';

  out.writeln(
      'func ($receiver *$className) ${method.name.lexeme}($paramGo)$returnGo {');
  deps.methodScope = MethodScope(receiver);
  final body = method.body;
  if (body is BlockFunctionBody) {
    for (final statement in body.block.statements) {
      _writeStatement(statement, out, deps, indent: '\t');
    }
  } else if (body is ExpressionFunctionBody) {
    if (isVoidReturn) {
      _writeExpressionStatement(body.expression, out, deps, indent: '\t');
    } else {
      out.writeln('\treturn ${_writeExpression(body.expression, deps)}');
    }
  }
  deps.methodScope = null;
  out.writeln('}');
  out.writeln();
}

/// The Go type expression for a Dart type the checker has already confirmed
/// is supported (`_isSupportedType`) — used for parameter and return types,
/// which (unlike locals) Go's syntax requires spelling out explicitly. A
/// `@GoType` here also registers its binding's import, since a type used
/// only in a signature (never itself the target of a method call) would
/// otherwise never trigger that registration. A user enum's Go type is its
/// own generated name (`Mode`, see [_writeEnumDeclaration]); a `@GoType`
/// binding enum's type is the annotated Go type expression, same as any
/// other binding (`isGoType`). Recorded in `docs/mapping.md`.
String _goTypeName(DartType type, GoDeps deps) {
  if (type.isDartCoreInt) return 'int';
  if (type.isDartCoreDouble) return 'float64';
  if (type.isDartCoreBool) return 'bool';
  if (type.isDartCoreString) return 'string';
  if (_isListOfInt(type)) return '[]byte';
  if (isGoType(type)) {
    final element = (type as InterfaceType).element;
    final import = goImportOf(element.library);
    if (import != null) _useImport(import, deps);
    return goTypeOf(element)!;
  }
  if (type is InterfaceType && type.element is EnumElement) {
    return type.element.name!;
  }
  if (type is InterfaceType && type.element is ClassElement) {
    // A user class instance is always `*Foo` (#32, `docs/mapping.md`: Dart
    // reference semantics, `==` is identity).
    return '*${type.element.name}';
  }
  throw StateError('unchecked Go type: ${type.getDisplayString()}');
}

void _writeStatement(
  Statement statement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  switch (statement) {
    case VariableDeclarationStatement():
      for (final variable in statement.variables.variables) {
        final initializer = variable.initializer!;
        final name = variable.name.lexeme;
        if (initializer is CascadeExpression) {
          // Reuses the local's own name as the cascade's receiver instead
          // of minting a `_t0`-style temporary (see
          // [_writeCascadeExpressionStatement]) — the local already names
          // the value.
          out.writeln(
              '$indent$name := ${_writeExpression(initializer.target, deps)}');
          _writeCascadeSections(initializer, name, out, deps, indent: indent);
        } else {
          out.writeln('$indent$name := ${_writeExpression(initializer, deps)}');
        }
      }

    case WhileStatement():
      final condition = statement.condition;
      // `while (true)` is idiomatic Go's bare `for {`; any other condition
      // becomes `for <cond> {`, which is Go's "while" form.
      final isBareTrue = condition is BooleanLiteral && condition.value == true;
      out.writeln(isBareTrue
          ? '${indent}for {'
          : '${indent}for ${_writeExpression(condition, deps)} {');
      for (final inner in (statement.body as Block).statements) {
        _writeStatement(inner, out, deps, indent: '$indent\t');
      }
      out.writeln('$indent}');

    case ForStatement():
      _writeForStatement(statement, out, deps, indent: indent);

    case BreakStatement():
      out.writeln('${indent}break');

    case ContinueStatement():
      out.writeln('${indent}continue');

    case ExpressionStatement():
      _writeExpressionStatement(statement.expression, out, deps,
          indent: indent);

    case IfStatement():
      _writeIfStatement(statement, out, deps, indent: indent);

    case SwitchStatement():
      _writeSwitchStatement(statement, out, deps, indent: indent);

    case ReturnStatement():
      final value = statement.expression;
      out.writeln(value == null
          ? '${indent}return'
          : '${indent}return ${_writeExpression(value, deps)}');

    default:
      throw StateError(
        'generator received unchecked statement: ${statement.runtimeType}. '
        'This is a bug: checkEntryPoint() should have rejected it first.',
      );
  }
}

/// `if (cond) { ... } else if (cond2) { ... } else { ... }` maps 1:1 onto Go,
/// which has the same `if`/`else if`/`else` shape. `else if` is Dart's own
/// `elseStatement` being another `IfStatement` (see `checker.dart`), so
/// recursing on it here reproduces the chain; a plain `else` block ends it.
void _writeIfStatement(
  IfStatement statement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  out.writeln('${indent}if ${_writeExpression(statement.expression, deps)} {');
  for (final inner in (statement.thenStatement as Block).statements) {
    _writeStatement(inner, out, deps, indent: '$indent\t');
  }
  _writeElseBranch(statement.elseStatement, out, deps, indent: indent);
}

void _writeElseBranch(
  Statement? elseStatement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  if (elseStatement == null) {
    out.writeln('$indent}');
    return;
  }
  if (elseStatement is IfStatement) {
    final condition = _writeExpression(elseStatement.expression, deps);
    out.writeln('$indent} else if $condition {');
    for (final inner in (elseStatement.thenStatement as Block).statements) {
      _writeStatement(inner, out, deps, indent: '$indent\t');
    }
    _writeElseBranch(elseStatement.elseStatement, out, deps, indent: indent);
    return;
  }
  out.writeln('$indent} else {');
  for (final inner in (elseStatement as Block).statements) {
    _writeStatement(inner, out, deps, indent: '$indent\t');
  }
  out.writeln('$indent}');
}

/// `for (var i = <init>; <cond>; <updater>) { ... }` maps 1:1 onto Go's own
/// C-style `for`, which has the same three-clause shape (the checker limits
/// Dart's more permissive form — multiple declarations, multiple updaters,
/// a reused loop variable — to what Go's syntax can express directly).
void _writeForStatement(
  ForStatement statement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  final parts = statement.forLoopParts as ForPartsWithDeclarations;
  final variable = parts.variables.variables.single;
  final init = '${variable.name.lexeme} := '
      '${_writeExpression(variable.initializer!, deps)}';
  final condition = _writeExpression(parts.condition!, deps);
  final updater = _writeUpdaterExpression(parts.updaters.single, deps);
  out.writeln('$indent' 'for $init; $condition; $updater {');
  for (final inner in (statement.body as Block).statements) {
    _writeStatement(inner, out, deps, indent: '$indent\t');
  }
  out.writeln('$indent}');
}

/// `switch (mode) { case 0: ... case 1: case 2: ... default: ... }` maps
/// onto Go's own `switch`, which shares Dart's no-fallthrough semantics
/// (`docs/mapping.md`). Consecutive empty Dart cases (`case 1: case 2: ...`)
/// are grouping syntax, not statements — they're merged into a single Go
/// `case 1, 2:` clause. An empty case immediately before `default` is
/// dropped rather than merged: Go's `default` has no value list to merge
/// into, but it already matches any value no other `case` claims, which is
/// exactly what an empty case falling into `default` means.
void _writeSwitchStatement(
  SwitchStatement statement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  out.writeln(
      '${indent}switch ${_writeExpression(statement.expression, deps)} {');

  final pendingValues = <String>[];
  for (final member in statement.members) {
    switch (member) {
      case SwitchPatternCase():
        final pattern = member.guardedPattern.pattern as ConstantPattern;
        pendingValues.add(_writeExpression(pattern.expression, deps));
        if (member.statements.isEmpty) continue;
        out.writeln('${indent}case ${pendingValues.join(', ')}:');
        pendingValues.clear();
        for (final inner in member.statements) {
          _writeStatement(inner, out, deps, indent: '$indent\t');
        }
      case SwitchDefault():
        pendingValues.clear();
        out.writeln('${indent}default:');
        for (final inner in member.statements) {
          _writeStatement(inner, out, deps, indent: '$indent\t');
        }
      case SwitchCase():
        throw StateError(
          'generator received unchecked SwitchCase member. This is a bug: '
          'checkEntryPoint() should have rejected it first.',
        );
    }
  }
  if (pendingValues.isNotEmpty) {
    out.writeln('${indent}case ${pendingValues.join(', ')}:');
  }

  out.writeln('$indent}');
}

void _writeExpressionStatement(
  Expression expression,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  if (expression is CascadeExpression) {
    _writeCascadeExpressionStatement(expression, out, deps, indent: indent);
    return;
  }

  if (expression is AssignmentExpression &&
      expression.leftHandSide is IndexExpression) {
    // `data[i] = v;`: not a compound assignment, so it doesn't go through
    // _writeUpdaterExpression (whose AssignmentExpression case assumes a
    // bare local target).
    _writeListIndexWrite(expression, out, deps, indent: indent);
    return;
  }

  if (expression is PostfixExpression || expression is AssignmentExpression) {
    out.writeln('$indent${_writeUpdaterExpression(expression, deps)}');
    return;
  }

  if (expression is MethodInvocation) {
    if (expression.target == null) {
      switch (expression.methodName.name) {
        case 'print':
          final arg = _writePrintArgument(
              expression.argumentList.arguments.single, deps);
          out.writeln('${indent}println($arg)');
          return;
        case 'sleep':
          deps.imports['time'] = null;
          final duration = _writeDurationExpression(
            expression.argumentList.arguments.single
                as InstanceCreationExpression,
          );
          out.writeln('${indent}time.Sleep($duration)');
          return;
      }
    }
    final listAdd = _writeListAdd(expression, deps);
    if (listAdd != null) {
      out.writeln('$indent$listAdd');
      return;
    }
    final localCall = _writeLocalFunctionCall(expression, deps);
    if (localCall != null) {
      out.writeln('$indent$localCall');
      return;
    }
    final bound = _writeBoundCall(expression, deps);
    if (bound != null) {
      out.writeln('$indent$bound');
      return;
    }
    final instanceCall = _writeInstanceMethodCall(expression, deps);
    if (instanceCall != null) {
      out.writeln('$indent$instanceCall');
      return;
    }
  }

  throw StateError(
    'generator received unchecked expression statement: '
    '${expression.runtimeType}. This is a bug: checkEntryPoint() should '
    'have rejected it first.',
  );
}

/// `data[i] = v;`: Go's `[]byte` element type is `byte`, but Dart's `v` is
/// `int`, so the write needs an explicit `byte(v)` cast — the read side
/// gets the matching `int(...)` cast in `_writeExpression`'s
/// `IndexExpression` case. Recorded in `docs/mapping.md`.
void _writeListIndexWrite(
  AssignmentExpression expression,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  final index = expression.leftHandSide as IndexExpression;
  final target = (index.target as SimpleIdentifier).name;
  final indexValue = _writeExpression(index.index, deps);
  final rhs = _writeExpression(expression.rightHandSide, deps);
  out.writeln('$indent$target[$indexValue] = byte($rhs)');
}

/// `data.add(v);`: `List.add` mutates in place and returns `void` in Dart;
/// Go's `append` returns a new slice that must be reassigned. `byte(v)` for
/// the same reason as index writes. Recorded in `docs/mapping.md`.
///
/// Returns `null` (not writing anything) when [call] isn't `.add(...)` on a
/// `List<int>` — the checker (`_checkListAdd`) already confirmed the shape
/// for any call that reaches here as a statement, but this still checks the
/// receiver type to correctly fall through to [_writeBoundCall] for an
/// ordinary binding method that happens to be named `add`.
String? _writeListAdd(MethodInvocation call, GoDeps deps) {
  if (call.methodName.name != 'add') return null;
  final target = call.target;
  if (target is! SimpleIdentifier || !_isListOfInt(target.staticType)) {
    return null;
  }
  final value = _writeExpression(call.argumentList.arguments.single, deps);
  return '${target.name} = append(${target.name}, byte($value))';
}

/// A for-loop updater or a compound-assignment statement: `x++`/`x--` map
/// onto the same Go postfix operators; `x += y` (`+=`/`-=`/`*=`/`/=`) maps
/// onto Go's identical compound-assignment tokens; `x ~/= y` becomes `x /=
/// y` (same reasoning as `~/`); `x %= y` can't reuse Go's `%=` (same
/// negative-result mismatch as `%`), so it becomes the equivalent statement
/// `x = dartrt.Mod(x, y)` — valid both as its own statement and as a Go
/// for-loop post-clause. Recorded in `docs/mapping.md`.
String _writeUpdaterExpression(Expression expression, GoDeps deps) {
  if (expression is PostfixExpression) {
    final target =
        _writeWriteTarget(expression.operand, expression.writeElement, deps);
    return '$target${expression.operator.lexeme}';
  }
  if (expression is AssignmentExpression) {
    final target = _writeWriteTarget(
        expression.leftHandSide, expression.writeElement, deps);
    final rhs = _writeExpression(expression.rightHandSide, deps);
    final op = expression.operator.lexeme;
    if (op == '%=') return '$target = ${_useDartrt(deps)}.Mod($target, $rhs)';
    if (op == '~/=') return '$target /= $rhs';
    return '$target $op $rhs';
  }
  throw StateError('unchecked updater expression: ${expression.runtimeType}');
}

/// [target] (a `PostfixExpression`'s operand, or an `AssignmentExpression`'s
/// `leftHandSide`) as a Go lvalue: a bare local's own name, or — when
/// [writeElement] is a `SetterElement`, #32 — a field write (`c.value`/
/// `this.value`/bare `value` with implicit `this`), qualified with its
/// receiver the same way a read is ([_writeFieldAccess]). [writeElement]
/// (not [target] itself) is the reliable way to tell the two apart: a
/// write-only position like this leaves `target`'s own `.element` `null`
/// (see `docs/mapping.md`), unlike a value-position read.
String _writeWriteTarget(
    Expression target, Element? writeElement, GoDeps deps) {
  if (writeElement is! SetterElement) return (target as SimpleIdentifier).name;

  final Expression? receiverTarget;
  final String name;
  switch (target) {
    case SimpleIdentifier():
      receiverTarget = null;
      name = target.name;
    case PrefixedIdentifier():
      receiverTarget = target.prefix;
      name = target.identifier.name;
    case PropertyAccess():
      receiverTarget = target.target;
      name = target.propertyName.name;
    default:
      throw StateError('unchecked field write target: ${target.runtimeType}');
  }
  final receiver = receiverTarget == null || receiverTarget is ThisExpression
      ? deps.methodScope!.receiver
      : _writeExpression(receiverTarget, deps);
  return '$receiver.$name';
}

/// `print(x)` takes any `String` expression; interpolation is concatenated
/// per type (`docs/mapping.md`, "String interpolation"): `int` via
/// `strconv.Itoa`, `bool` via `strconv.FormatBool`, `String` verbatim. No
/// `fmt` in the generated code.
String _writePrintArgument(Expression argument, GoDeps deps) {
  if (argument is StringInterpolation) {
    final parts = <String>[];
    for (final element in argument.elements) {
      if (element is InterpolationString) {
        if (element.value.isNotEmpty) {
          parts.add(_goStringLiteral(element.value));
        }
      } else if (element is InterpolationExpression) {
        final inner = element.expression;
        final value = _writeExpression(inner, deps);
        final type = inner.staticType!;
        if (type.isDartCoreString) {
          parts.add(value);
        } else if (type.isDartCoreInt) {
          deps.imports['strconv'] = null;
          parts.add('strconv.Itoa($value)');
        } else if (type.isDartCoreBool) {
          deps.imports['strconv'] = null;
          parts.add('strconv.FormatBool($value)');
        } else if (type.isDartCoreDouble) {
          parts.add('${_useDartrt(deps)}.FormatDouble($value)');
        } else {
          throw StateError(
              'unchecked interpolation of ${type.getDisplayString()}');
        }
      }
    }
    if (parts.isEmpty) {
      return '""';
    }
    return parts.join(' + ');
  }
  return _writeExpression(argument, deps);
}

/// Named args on `Duration(...)` (days/hours/minutes/seconds/milliseconds/
/// microseconds) become `n * time.Xxx` terms summed together, matching Go's
/// `time.Duration` arithmetic. Recorded in `docs/mapping.md`.
String _writeDurationExpression(InstanceCreationExpression creation) {
  const goUnit = {
    'microseconds': 'time.Microsecond',
    'milliseconds': 'time.Millisecond',
    'seconds': 'time.Second',
    'minutes': 'time.Minute',
    'hours': 'time.Hour',
    'days': 'time.Hour * 24',
  };

  final terms = <String>[];
  for (final argument in creation.argumentList.arguments) {
    final named = argument as NamedExpression;
    final value = (named.expression as IntegerLiteral).value!;
    terms.add('$value * ${goUnit[named.name.label.name]}');
  }
  return terms.join(' + ');
}

/// Value expressions the checker accepts, each emitted as one Go expression.
/// Literals stay untyped Go constants, so `x := 0` / `x := 0.5` / `x := true`
/// infer `int` / `float64` / `bool` exactly as `docs/mapping.md` decides.
String _writeExpression(Expression expression, GoDeps deps) {
  if (expression is IntegerLiteral) {
    // Dart lets an int literal stand for a double (`double d = 2;`); Go
    // would infer `int` from a bare `2`, so keep the float-ness explicit.
    final isDouble = expression.staticType?.isDartCoreDouble ?? false;
    return isDouble ? '${expression.value}.0' : '${expression.value}';
  }
  if (expression is DoubleLiteral) {
    return expression.literal.lexeme;
  }
  if (expression is BooleanLiteral) {
    return expression.value ? 'true' : 'false';
  }
  if (expression is SimpleStringLiteral) {
    return _goStringLiteral(expression.value);
  }
  if (expression is Identifier) {
    final builtinGetter = _writeBuiltinGetter(expression, deps);
    if (builtinGetter != null) return builtinGetter;
    final constant = _writeConstantReference(expression, deps);
    if (constant != null) return constant;
    final field = _writeFieldAccess(expression, deps);
    if (field != null) return field;
    return expression.name;
  }
  if (expression is PropertyAccess) {
    final builtinGetter = _writeBuiltinGetter(expression, deps);
    if (builtinGetter != null) return builtinGetter;
    final field = _writeFieldAccess(expression, deps);
    if (field != null) return field;
  }
  if (expression is MethodInvocation) {
    final conversion = _writeNumConversion(expression, deps);
    if (conversion != null) return conversion;
    final substring = _writeSubstring(expression, deps);
    if (substring != null) return substring;
    final localCall = _writeLocalFunctionCall(expression, deps);
    if (localCall != null) return localCall;
    final bound = _writeBoundCall(expression, deps);
    if (bound != null) return bound;
    final instanceCall = _writeInstanceMethodCall(expression, deps);
    if (instanceCall != null) return instanceCall;
  }
  if (expression is InstanceCreationExpression) {
    final fromCharCodes = _writeFromCharCodes(expression, deps);
    if (fromCharCodes != null) return fromCharCodes;
    final classConstruction = _writeClassConstruction(expression, deps);
    if (classConstruction != null) return classConstruction;
  }
  if (expression is ListLiteral) {
    final elements = expression.elements
        .cast<Expression>()
        .map((element) => 'byte(${_writeExpression(element, deps)})')
        .join(', ');
    return '[]byte{$elements}';
  }
  if (expression is IndexExpression) {
    final target = _writeExpression(expression.target!, deps);
    final index = _writeExpression(expression.index, deps);
    return 'int($target[$index])';
  }
  if (expression is ParenthesizedExpression) {
    return '(${_writeExpression(expression.expression, deps)})';
  }
  if (expression is BinaryExpression) {
    final op = expression.operator.lexeme;
    final left = _writeExpression(expression.leftOperand, deps);
    final right = _writeExpression(expression.rightOperand, deps);
    // Comparison (==/!=/</<=/>/>=), logical (&&/||), and int + - * use the
    // same tokens in Go as in Dart. `~/` (truncating division) is Go's `/`;
    // `%` goes through `dartrt.Mod` because Dart's `%` is never negative,
    // unlike Go's. Recorded in `docs/mapping.md`.
    if (op == '~/') return '$left / $right';
    if (op == '%') return '${_useDartrt(deps)}.Mod($left, $right)';
    return '$left $op $right';
  }
  if (expression is PrefixExpression && expression.operator.lexeme == '!') {
    return '!${_writeExpression(expression.operand, deps)}';
  }
  if (expression is PrefixExpression && expression.operator.lexeme == '-') {
    return '-${_writeExpression(expression.operand, deps)}';
  }
  throw StateError('unchecked expression: ${expression.runtimeType}');
}

/// A `@GoName` on an `external` top-level or static getter names a Go
/// constant or package-level variable, emitted as the bare (package-
/// qualified) identifier: `red` / `Button.a` → `rt.Red` / `rt.ButtonA`. An
/// enum constant reference (#31) is handled by [_writeEnumConstantReference]
/// instead — an enum constant getter is never `external`, so it can't share
/// this function's `goBindingOf` lookup. Recorded in `docs/mapping.md`.
String? _writeConstantReference(Identifier reference, GoDeps deps) {
  final enumReference = _writeEnumConstantReference(reference, deps);
  if (enumReference != null) return enumReference;
  final element = reference.element;
  if (element is! GetterElement || !element.isStatic) return null;
  final binding = goBindingOf(element);
  if (binding == null) return null;
  _useImport(binding.import, deps);
  return binding.goName;
}

/// `Mode.on` (a user enum) → the generated Go constant name (`ModeOn`, see
/// [_writeEnumDeclaration]). `Pin.led` (a `@GoType` binding enum) → its
/// `@GoName` value, exactly like [_writeConstantReference] does for an
/// `external static` getter (#31, `docs/mapping.md`).
String? _writeEnumConstantReference(Identifier reference, GoDeps deps) {
  final element = reference.element;
  if (element is! GetterElement) return null;
  final variable = element.variable;
  if (variable is! FieldElement || !variable.isEnumConstant) return null;
  final enumElement = variable.enclosingElement;
  if (enumElement is! EnumElement) return null;

  final goTypeName = goTypeOf(enumElement);
  if (goTypeName == null) {
    return '${enumElement.name}${_capitalize(variable.name!)}';
  }
  final goName = goNameOf(variable)!;
  final import = goImportOf(enumElement.library)!;
  _useImport(import, deps);
  return goName;
}

/// `.toDouble()`/`.toInt()`/`.round()` (`docs/mapping.md`): `int.toDouble()`
/// → `float64(x)`, `double.toInt()` → `int(x)` (Go's int-from-float64
/// conversion truncates toward zero, like Dart's), `double.round()` →
/// `int(math.Round(x))` (Go's `math.Round` rounds half away from zero, like
/// Dart's). The checker (`_checkNumConversion`) already confirmed the
/// receiver type and zero-argument shape, so this only needs to recognize
/// the same three names by receiver type — same disambiguation, so an
/// ordinary call that merely shares one of these names (receiver not
/// int/double) safely falls through to [_writeBoundCall] instead.
String? _writeNumConversion(MethodInvocation call, GoDeps deps) {
  final target = call.target;
  if (target == null) return null;
  final targetType = target.staticType;
  if (targetType == null) return null;
  final value = _writeExpression(target, deps);
  switch (call.methodName.name) {
    case 'toDouble' when targetType.isDartCoreInt:
      return 'float64($value)';
    case 'toInt' when targetType.isDartCoreDouble:
      return 'int($value)';
    case 'round' when targetType.isDartCoreDouble:
      deps.imports['math'] = null;
      return 'int(math.Round($value))';
    default:
      return null;
  }
}

/// `.length` (`String` or `List<int>` receiver), `.codeUnits` (`String`
/// receiver), and, on a user enum value (#31), `.name`/`.index` — see
/// checker.dart's `_checkBuiltinGetter` for the two AST shapes this
/// recognizes (`PrefixedIdentifier` for a bare-identifier receiver,
/// `PropertyAccess` otherwise). `.length` → Go's `len(x)` (works for both
/// `string` and `[]byte`); `.codeUnits` → `[]byte(s)`; `.name` → the
/// generated name table indexed by the value itself (`modeNames[m]`, no
/// cast needed — see [_writeEnumDeclaration]); `.index` → `int(m)` (an
/// explicit cast: `m`'s Go type is the enum's own defined type, not `int`,
/// matching the project's no-implicit-casts precedent). `docs/mapping.md`.
String? _writeBuiltinGetter(Expression expression, GoDeps deps) {
  final Expression target;
  final String name;
  switch (expression) {
    case PrefixedIdentifier():
      target = expression.prefix;
      name = expression.identifier.name;
    case PropertyAccess():
      final propertyTarget = expression.target;
      if (propertyTarget == null) return null;
      target = propertyTarget;
      name = expression.propertyName.name;
    default:
      return null;
  }

  if (name == 'name' || name == 'index') {
    final targetType = target.staticType;
    if (targetType is! InterfaceType || targetType.element is! EnumElement) {
      return null;
    }
    final enumElement = targetType.element as EnumElement;
    if (goTypeOf(enumElement) != null) return null;
    final value = _writeExpression(target, deps);
    return name == 'index'
        ? 'int($value)'
        : '${_lowerFirst(enumElement.name!)}Names[$value]';
  }

  if (name != 'length' && name != 'codeUnits') return null;
  final value = _writeExpression(target, deps);
  return name == 'codeUnits' ? '[]byte($value)' : 'len($value)';
}

/// `String.fromCharCodes(bytes)`, a named constructor
/// (`InstanceCreationExpression`, the same AST shape as `Duration(...)`) →
/// Go's `string(bytes)` conversion. `docs/mapping.md`.
String? _writeFromCharCodes(InstanceCreationExpression creation, GoDeps deps) {
  final typeName = creation.constructorName.type.name.lexeme;
  final constructorName = creation.constructorName.name?.name;
  if (typeName != 'String' || constructorName != 'fromCharCodes') return null;
  final value = _writeExpression(creation.argumentList.arguments.single, deps);
  return 'string($value)';
}

/// `s.substring(start, [end])` on a `String` receiver → Go's
/// `x[start:end]` (or `x[start:]` with no `end`) slice syntax.
/// `docs/mapping.md`.
String? _writeSubstring(MethodInvocation call, GoDeps deps) {
  if (call.methodName.name != 'substring') return null;
  final target = call.target;
  if (target == null) return null;
  final targetType = target.staticType;
  if (targetType == null || !targetType.isDartCoreString) return null;

  final value = _writeExpression(target, deps);
  final args = call.argumentList.arguments;
  final start = _writeExpression(args[0], deps);
  if (args.length == 1) return '$value[$start:]';
  final end = _writeExpression(args[1], deps);
  return '$value[$start:$end]';
}

/// `List<int>` maps to Go `[]byte` — see checker.dart's `_isListOfInt`.
bool _isListOfInt(DartType? type) {
  if (type is! InterfaceType || !type.isDartCoreList) return false;
  final args = type.typeArguments;
  return args.length == 1 && args.single.isDartCoreInt;
}

/// A call to a top-level Dart function declared in this same file (not an
/// `external` binding — see checker.dart's `_isLocalFunctionCall`) maps 1:1
/// onto a Go call of the same name, since it's declared right alongside
/// `main()` in the same generated file. `docs/mapping.md`.
String? _writeLocalFunctionCall(MethodInvocation call, GoDeps deps) {
  final callee = call.methodName.element;
  if (call.target != null ||
      callee is! TopLevelFunctionElement ||
      callee.isExternal) {
    return null;
  }
  final args = call.argumentList.arguments
      .map((arg) => _writeExpression(arg, deps))
      .join(', ');
  return '${call.methodName.name}($args)';
}

/// `@GoName` calls map 1:1 onto Go calls: a top-level binding becomes
/// `<goName>(args)` (the name is already package-qualified, e.g.
/// `wio.NewDisplay`), a method binding becomes `<receiver>.<goName>(args)`.
/// The receiver is written with [_writeExpression], not just a bare
/// identifier: method chaining (#30) means it may itself be another bound
/// call, which recurses back into this function. The binding library's
/// `@GoImport` is recorded so the import block and, for in-tree runtimes,
/// the `go.mod` `replace` are emitted. Recorded in `docs/mapping.md`.
String? _writeBoundCall(MethodInvocation call, GoDeps deps) {
  final callee = call.methodName.element;
  if (callee is! ExecutableElement) return null;
  final binding = goBindingOf(callee);
  if (binding == null) return null;

  _useImport(binding.import, deps);

  final args = call.argumentList.arguments
      .map((arg) => _writeExpression(arg, deps))
      .join(', ');
  final target = call.target;
  if (target == null) {
    return '${binding.goName}($args)';
  }
  return '${_writeExpression(target, deps)}.${binding.goName}($args)';
}

/// A call to an instance method of a user class (#32, `docs/mapping.md`):
/// `c.inc()`, `this.inc()`, or a bare `inc()` inside another method/
/// constructor of the same class (implicit `this`) — the class counterpart
/// of [_writeBoundCall]. `this`/implicit-`this` become the enclosing
/// method's own receiver variable ([GoDeps.methodScope]), the same way
/// [_writeFieldAccess] resolves them.
///
/// Returns `null` when [call] isn't this shape, so the caller falls through
/// to its usual call handling.
String? _writeInstanceMethodCall(MethodInvocation call, GoDeps deps) {
  final callee = call.methodName.element;
  if (callee is! MethodElement || callee.isExternal || callee.isStatic) {
    return null;
  }
  final args = call.argumentList.arguments
      .map((arg) => _writeExpression(arg, deps))
      .join(', ');
  final target = call.target;
  final receiver = target == null || target is ThisExpression
      ? deps.methodScope!.receiver
      : _writeExpression(target, deps);
  return '$receiver.${call.methodName.name}($args)';
}

/// A field access — implicit `this` (`value`), `this.value`, or `c.value`
/// on a local/field holding a user-class instance (#32, `docs/mapping.md`).
/// Every shape maps onto the same Go form, `<receiver>.<field>` — `this`
/// becomes the enclosing method's own receiver variable
/// ([GoDeps.methodScope]).
///
/// Returns `null` when [expression] isn't a field access, so the caller
/// falls through to its usual identifier/property handling.
String? _writeFieldAccess(Expression expression, GoDeps deps) {
  final Expression? target;
  final Element? element;
  final String name;
  switch (expression) {
    case SimpleIdentifier():
      target = null;
      element = expression.element;
      name = expression.name;
    case PrefixedIdentifier():
      target = expression.prefix;
      element = expression.identifier.element;
      name = expression.identifier.name;
    case PropertyAccess():
      final propertyTarget = expression.target;
      if (propertyTarget == null) return null;
      target = propertyTarget;
      element = expression.propertyName.element;
      name = expression.propertyName.name;
    default:
      return null;
  }
  if (element is! GetterElement || element.variable is! FieldElement) {
    return null;
  }
  final receiver = target == null || target is ThisExpression
      ? deps.methodScope!.receiver
      : _writeExpression(target, deps);
  return '$receiver.$name';
}

/// `Counter(0)` — a call to a user class's own (non-`@GoType`) generative
/// constructor, #32 → `NewCounter(0)` (`docs/mapping.md`).
///
/// `Pin(3)` — a `@GoType` class's own `external`, `@GoName`'d constructor
/// (#21) → its binding, exactly like a top-level binding call
/// ([_writeBoundCall]) since a `@GoType` value is otherwise only ever
/// produced by a top-level binding function (`docs/writing_bindings.md`).
///
/// Returns `null` when [creation] is neither shape, so the caller falls
/// through to its usual unsupported-expression handling.
String? _writeClassConstruction(
  InstanceCreationExpression creation,
  GoDeps deps,
) {
  final element = creation.constructorName.element;
  if (element is! ConstructorElement) return null;
  final cls = element.enclosingElement;
  if (cls is! ClassElement) return null;

  final args = creation.argumentList.arguments
      .map((arg) => _writeExpression(arg, deps))
      .join(', ');

  if (goTypeOf(cls) != null) {
    final binding = goBindingOf(element);
    if (binding == null) return null;
    _useImport(binding.import, deps);
    return '${binding.goName}($args)';
  }

  return 'New${cls.name}($args)';
}

/// `a..b()..c()`: not a single Go expression, so this only handles the two
/// syntactic positions the checker accepts it in — an `ExpressionStatement`
/// ([_writeCascadeExpressionStatement]) and a local's initializer (inline
/// in [_writeStatement]'s `VariableDeclarationStatement` case, which reuses
/// the local's own name as [receiver] instead of minting a temporary).
/// [receiver] is written once up front by the caller (`receiver := target`);
/// every cascade section then becomes its own `receiver.goName(args)`
/// statement — the same shape [_writeBoundCall] would produce for a
/// non-cascaded call on that receiver.
void _writeCascadeSections(
  CascadeExpression expression,
  String receiver,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  for (final section in expression.cascadeSections) {
    final call = section as MethodInvocation;
    final callee = call.methodName.element as ExecutableElement;
    final binding = goBindingOf(callee)!;
    _useImport(binding.import, deps);
    final args = call.argumentList.arguments
        .map((arg) => _writeExpression(arg, deps))
        .join(', ');
    out.writeln('$indent$receiver.${binding.goName}($args)');
  }
}

void _writeCascadeExpressionStatement(
  CascadeExpression expression,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  final receiver = '_t${deps.nextTempId++}';
  out.writeln(
      '$indent$receiver := ${_writeExpression(expression.target, deps)}');
  _writeCascadeSections(expression, receiver, out, deps, indent: indent);
}

void _useImport(GoImportSpec import, GoDeps deps) {
  deps.imports[import.path] = import.alias;
  final local = import.localModule;
  if (local != null) {
    deps.localModules[local.modulePath] = local;
  }
}

/// Locates `packages/dart2tinygo/go/` the same way a binding's `go/` is
/// found (`findLocalModuleNear`, walking up from a Dart source file to its
/// `pubspec.yaml`) — except dartrt isn't declared by any `@GoImport`, so the
/// source file is this very library's own location, resolved via
/// `package:dart2tinygo`'s package config rather than the entry point's
/// (the entry point's own package graph has no reason to depend on
/// `dart2tinygo`).
Future<GoLocalModule?> _resolveDartrtModule() async {
  final fileUri = await Isolate.resolvePackageUri(
    Uri.parse('package:dart2tinygo/src/backend/generator.dart'),
  );
  if (fileUri == null) return null;
  return findLocalModuleNear(fileUri.toFilePath());
}

/// Registers `dartrt` as an import (only when actually used, like any other
/// Go import) and returns the identifier to call it through.
String _useDartrt(GoDeps deps) {
  final module = deps.dartrtModule;
  if (module == null) {
    throw StateError(
      'dartrt runtime not found (packages/dart2tinygo/go/ is missing from '
      'this checkout); this is a packaging bug, not unsupported syntax.',
    );
  }
  _useImport(
    GoImportSpec(path: module.modulePath, alias: 'dartrt', localModule: module),
    deps,
  );
  return 'dartrt';
}

String _goStringLiteral(String content) {
  final escaped = content
      .replaceAll(r'\', r'\\')
      .replaceAll('"', r'\"')
      .replaceAll('\n', r'\n')
      .replaceAll('\t', r'\t');
  return '"$escaped"';
}
