import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';

/// The result of converting a checked entry point to Go source, per
/// `HANDOFF_dart2tinygo.md` §4.2/§4.4: no `fmt.Sprintf`, string
/// interpolation is concatenated with `strconv` based on type.
///
/// Callers must have already run [checkEntryPoint] and confirmed there are
/// no [UnsupportedSyntaxError]s; this generator assumes the AST matches the
/// v0.1 minimal subset and does not re-validate it.
class GeneratedGoFile {
  GeneratedGoFile(this.source);

  final String source;
}

/// Converts the `main()` function of a checked [ResolvedUnitResult] into a
/// single-file Go program.
GeneratedGoFile generateGoFile(ResolvedUnitResult result) {
  final mainDecl = result.unit.declarations
      .whereType<FunctionDeclaration>()
      .firstWhere((d) => d.name.lexeme == 'main');
  final body = (mainDecl.functionExpression.body as BlockFunctionBody).block;

  final imports = <String>{};
  final bodyBuffer = StringBuffer();
  for (final statement in body.statements) {
    _writeStatement(statement, bodyBuffer, imports, indent: '\t');
  }

  final out = StringBuffer()
    ..writeln('// Code generated by dart2tinygo. DO NOT EDIT.')
    ..writeln('package main')
    ..writeln();
  if (imports.isNotEmpty) {
    final sorted = imports.toList()..sort();
    if (sorted.length == 1) {
      out.writeln('import "${sorted.single}"');
    } else {
      out.writeln('import (');
      for (final import in sorted) {
        out.writeln('\t"$import"');
      }
      out.writeln(')');
    }
    out.writeln();
  }
  out
    ..writeln('func main() {')
    ..write(bodyBuffer)
    ..writeln('}');

  return GeneratedGoFile(out.toString());
}

void _writeStatement(
  Statement statement,
  StringBuffer out,
  Set<String> imports, {
  required String indent,
}) {
  switch (statement) {
    case VariableDeclarationStatement():
      for (final variable in statement.variables.variables) {
        final value = _writeExpression(variable.initializer!, imports);
        out.writeln('$indent${variable.name.lexeme} := $value');
      }

    case WhileStatement():
      out.writeln('${indent}for {');
      for (final inner in (statement.body as Block).statements) {
        _writeStatement(inner, out, imports, indent: '$indent\t');
      }
      out.writeln('$indent}');

    case ExpressionStatement():
      _writeExpressionStatement(statement.expression, out, imports,
          indent: indent);

    default:
      throw StateError(
        'generator received unchecked statement: ${statement.runtimeType}. '
        'This is a bug: checkEntryPoint() should have rejected it first.',
      );
  }
}

void _writeExpressionStatement(
  Expression expression,
  StringBuffer out,
  Set<String> imports, {
  required String indent,
}) {
  if (expression is PostfixExpression) {
    final target = (expression.operand as SimpleIdentifier).name;
    out.writeln('$indent$target${expression.operator.lexeme}');
    return;
  }

  if (expression is MethodInvocation) {
    switch (expression.methodName.name) {
      case 'print':
        final arg = _writePrintArgument(
            expression.argumentList.arguments.single, imports);
        out.writeln('${indent}println($arg)');
        return;
      case 'sleep':
        imports.add('time');
        final duration = _writeDurationExpression(
          expression.argumentList.arguments.single
              as InstanceCreationExpression,
        );
        out.writeln('${indent}time.Sleep($duration)');
        return;
    }
  }

  throw StateError(
    'generator received unchecked expression statement: '
    '${expression.runtimeType}. This is a bug: checkEntryPoint() should '
    'have rejected it first.',
  );
}

String _writePrintArgument(Expression argument, Set<String> imports) {
  if (argument is SimpleStringLiteral) {
    return _goStringLiteral(argument.value);
  }
  if (argument is StringInterpolation) {
    final parts = <String>[];
    for (final element in argument.elements) {
      if (element is InterpolationString) {
        if (element.value.isNotEmpty) {
          parts.add(_goStringLiteral(element.value));
        }
      } else if (element is InterpolationExpression) {
        imports.add('strconv');
        final name = (element.expression as SimpleIdentifier).name;
        parts.add('strconv.Itoa($name)');
      }
    }
    if (parts.isEmpty) {
      return '""';
    }
    return parts.join(' + ');
  }
  throw StateError('unchecked print() argument: ${argument.runtimeType}');
}

/// Named args on `Duration(...)` (days/hours/minutes/seconds/milliseconds/
/// microseconds) become `n * time.Xxx` terms summed together, matching Go's
/// `time.Duration` arithmetic. Recorded in `docs/mapping.md`.
String _writeDurationExpression(InstanceCreationExpression creation) {
  const goUnit = {
    'microseconds': 'time.Microsecond',
    'milliseconds': 'time.Millisecond',
    'seconds': 'time.Second',
    'minutes': 'time.Minute',
    'hours': 'time.Hour',
    'days': 'time.Hour * 24',
  };

  final terms = <String>[];
  for (final argument in creation.argumentList.arguments) {
    final named = argument as NamedExpression;
    final value = (named.expression as IntegerLiteral).value!;
    terms.add('$value * ${goUnit[named.name.label.name]}');
  }
  return terms.join(' + ');
}

String _writeExpression(Expression expression, Set<String> imports) {
  if (expression is IntegerLiteral) {
    return '${expression.value}';
  }
  if (expression is SimpleIdentifier) {
    return expression.name;
  }
  throw StateError('unchecked expression: ${expression.runtimeType}');
}

String _goStringLiteral(String content) {
  final escaped = content
      .replaceAll(r'\', r'\\')
      .replaceAll('"', r'\"')
      .replaceAll('\n', r'\n')
      .replaceAll('\t', r'\t');
  return '"$escaped"';
}
