import 'package:analyzer/dart/analysis/results.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:dart2tinygo/src/frontend/bindings.dart';

/// The result of converting a checked entry point to Go source, per
/// `HANDOFF_dart2tinygo.md` §4.2/§4.4: no `fmt.Sprintf`, string
/// interpolation is concatenated with `strconv` based on type.
///
/// Callers must have already run [checkEntryPoint] and confirmed there are
/// no [UnsupportedSyntaxError]s; this generator assumes the AST matches the
/// v0.1 minimal subset and does not re-validate it.
class GeneratedGoFile {
  GeneratedGoFile(this.source, {this.localModules = const []});

  final String source;

  /// Binding Go modules that live next to their Dart package (see
  /// `GoImportSpec.localModule`). The CLI turns each into a `require` +
  /// `replace` pair in the generated `go.mod` so the output builds from a
  /// checkout without publishing anything.
  final List<GoLocalModule> localModules;
}

/// Everything the generated file needs from outside itself, collected while
/// walking `main()`.
class GoDeps {
  /// Go imports keyed by import path. The value is the alias (`null` for
  /// stdlib packages and for bindings that rely on the package's own name).
  final imports = <String, String?>{};

  /// Binding modules with an in-tree Go runtime, keyed by module path so a
  /// binding used many times is required once.
  final localModules = <String, GoLocalModule>{};
}

/// Converts the `main()` function of a checked [ResolvedUnitResult] into a
/// single-file Go program.
GeneratedGoFile generateGoFile(ResolvedUnitResult result) {
  final mainDecl = result.unit.declarations
      .whereType<FunctionDeclaration>()
      .firstWhere((d) => d.name.lexeme == 'main');
  final body = (mainDecl.functionExpression.body as BlockFunctionBody).block;

  final deps = GoDeps();
  final imports = deps.imports;
  final bodyBuffer = StringBuffer();
  for (final statement in body.statements) {
    _writeStatement(statement, bodyBuffer, deps, indent: '\t');
  }

  final out = StringBuffer()
    ..writeln('// Code generated by dart2tinygo. DO NOT EDIT.')
    ..writeln('package main')
    ..writeln();
  if (imports.isNotEmpty) {
    final sorted = imports.keys.toList()..sort();
    String spec(String path) {
      final alias = imports[path];
      return alias == null ? '"$path"' : '$alias "$path"';
    }

    if (sorted.length == 1) {
      out.writeln('import ${spec(sorted.single)}');
    } else {
      out.writeln('import (');
      for (final import in sorted) {
        out.writeln('\t${spec(import)}');
      }
      out.writeln(')');
    }
    out.writeln();
  }
  out
    ..writeln('func main() {')
    ..write(bodyBuffer)
    ..writeln('}');

  return GeneratedGoFile(
    out.toString(),
    localModules: deps.localModules.values.toList(),
  );
}

void _writeStatement(
  Statement statement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  switch (statement) {
    case VariableDeclarationStatement():
      for (final variable in statement.variables.variables) {
        final value = _writeExpression(variable.initializer!, deps);
        out.writeln('$indent${variable.name.lexeme} := $value');
      }

    case WhileStatement():
      final condition = statement.condition;
      // `while (true)` is idiomatic Go's bare `for {`; any other condition
      // becomes `for <cond> {`, which is Go's "while" form.
      final isBareTrue = condition is BooleanLiteral && condition.value == true;
      out.writeln(isBareTrue
          ? '${indent}for {'
          : '${indent}for ${_writeExpression(condition, deps)} {');
      for (final inner in (statement.body as Block).statements) {
        _writeStatement(inner, out, deps, indent: '$indent\t');
      }
      out.writeln('$indent}');

    case ForStatement():
      _writeForStatement(statement, out, deps, indent: indent);

    case BreakStatement():
      out.writeln('${indent}break');

    case ContinueStatement():
      out.writeln('${indent}continue');

    case ExpressionStatement():
      _writeExpressionStatement(statement.expression, out, deps,
          indent: indent);

    case IfStatement():
      _writeIfStatement(statement, out, deps, indent: indent);

    default:
      throw StateError(
        'generator received unchecked statement: ${statement.runtimeType}. '
        'This is a bug: checkEntryPoint() should have rejected it first.',
      );
  }
}

/// `if (cond) { ... } else if (cond2) { ... } else { ... }` maps 1:1 onto Go,
/// which has the same `if`/`else if`/`else` shape. `else if` is Dart's own
/// `elseStatement` being another `IfStatement` (see `checker.dart`), so
/// recursing on it here reproduces the chain; a plain `else` block ends it.
void _writeIfStatement(
  IfStatement statement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  out.writeln('${indent}if ${_writeExpression(statement.expression, deps)} {');
  for (final inner in (statement.thenStatement as Block).statements) {
    _writeStatement(inner, out, deps, indent: '$indent\t');
  }
  _writeElseBranch(statement.elseStatement, out, deps, indent: indent);
}

void _writeElseBranch(
  Statement? elseStatement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  if (elseStatement == null) {
    out.writeln('$indent}');
    return;
  }
  if (elseStatement is IfStatement) {
    final condition = _writeExpression(elseStatement.expression, deps);
    out.writeln('$indent} else if $condition {');
    for (final inner in (elseStatement.thenStatement as Block).statements) {
      _writeStatement(inner, out, deps, indent: '$indent\t');
    }
    _writeElseBranch(elseStatement.elseStatement, out, deps, indent: indent);
    return;
  }
  out.writeln('$indent} else {');
  for (final inner in (elseStatement as Block).statements) {
    _writeStatement(inner, out, deps, indent: '$indent\t');
  }
  out.writeln('$indent}');
}

/// `for (var i = <init>; <cond>; <updater>) { ... }` maps 1:1 onto Go's own
/// C-style `for`, which has the same three-clause shape (the checker limits
/// Dart's more permissive form — multiple declarations, multiple updaters,
/// a reused loop variable — to what Go's syntax can express directly).
void _writeForStatement(
  ForStatement statement,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  final parts = statement.forLoopParts as ForPartsWithDeclarations;
  final variable = parts.variables.variables.single;
  final init = '${variable.name.lexeme} := '
      '${_writeExpression(variable.initializer!, deps)}';
  final condition = _writeExpression(parts.condition!, deps);
  final updater = _writeUpdaterExpression(parts.updaters.single, deps);
  out.writeln('$indent' 'for $init; $condition; $updater {');
  for (final inner in (statement.body as Block).statements) {
    _writeStatement(inner, out, deps, indent: '$indent\t');
  }
  out.writeln('$indent}');
}

void _writeExpressionStatement(
  Expression expression,
  StringBuffer out,
  GoDeps deps, {
  required String indent,
}) {
  if (expression is PostfixExpression || expression is AssignmentExpression) {
    out.writeln('$indent${_writeUpdaterExpression(expression, deps)}');
    return;
  }

  if (expression is MethodInvocation) {
    if (expression.target == null) {
      switch (expression.methodName.name) {
        case 'print':
          final arg = _writePrintArgument(
              expression.argumentList.arguments.single, deps);
          out.writeln('${indent}println($arg)');
          return;
        case 'sleep':
          deps.imports['time'] = null;
          final duration = _writeDurationExpression(
            expression.argumentList.arguments.single
                as InstanceCreationExpression,
          );
          out.writeln('${indent}time.Sleep($duration)');
          return;
      }
    }
    final bound = _writeBoundCall(expression, deps);
    if (bound != null) {
      out.writeln('$indent$bound');
      return;
    }
  }

  throw StateError(
    'generator received unchecked expression statement: '
    '${expression.runtimeType}. This is a bug: checkEntryPoint() should '
    'have rejected it first.',
  );
}

/// A for-loop updater or a compound-assignment statement: `x++`/`x--` map
/// onto the same Go postfix operators, and `x += y` (`+=`/`-=`/`*=`/`/=`)
/// onto Go's identical compound-assignment tokens. Recorded in
/// `docs/mapping.md`.
String _writeUpdaterExpression(Expression expression, GoDeps deps) {
  if (expression is PostfixExpression) {
    final target = (expression.operand as SimpleIdentifier).name;
    return '$target${expression.operator.lexeme}';
  }
  if (expression is AssignmentExpression) {
    final target = (expression.leftHandSide as SimpleIdentifier).name;
    final rhs = _writeExpression(expression.rightHandSide, deps);
    return '$target ${expression.operator.lexeme} $rhs';
  }
  throw StateError('unchecked updater expression: ${expression.runtimeType}');
}

/// `print(x)` takes any `String` expression; interpolation is concatenated
/// per type (`docs/mapping.md`, "String interpolation"): `int` via
/// `strconv.Itoa`, `bool` via `strconv.FormatBool`, `String` verbatim. No
/// `fmt` in the generated code.
String _writePrintArgument(Expression argument, GoDeps deps) {
  if (argument is StringInterpolation) {
    final parts = <String>[];
    for (final element in argument.elements) {
      if (element is InterpolationString) {
        if (element.value.isNotEmpty) {
          parts.add(_goStringLiteral(element.value));
        }
      } else if (element is InterpolationExpression) {
        final inner = element.expression;
        final value = _writeExpression(inner, deps);
        final type = inner.staticType!;
        if (type.isDartCoreString) {
          parts.add(value);
        } else if (type.isDartCoreInt) {
          deps.imports['strconv'] = null;
          parts.add('strconv.Itoa($value)');
        } else if (type.isDartCoreBool) {
          deps.imports['strconv'] = null;
          parts.add('strconv.FormatBool($value)');
        } else {
          throw StateError(
              'unchecked interpolation of ${type.getDisplayString()}');
        }
      }
    }
    if (parts.isEmpty) {
      return '""';
    }
    return parts.join(' + ');
  }
  return _writeExpression(argument, deps);
}

/// Named args on `Duration(...)` (days/hours/minutes/seconds/milliseconds/
/// microseconds) become `n * time.Xxx` terms summed together, matching Go's
/// `time.Duration` arithmetic. Recorded in `docs/mapping.md`.
String _writeDurationExpression(InstanceCreationExpression creation) {
  const goUnit = {
    'microseconds': 'time.Microsecond',
    'milliseconds': 'time.Millisecond',
    'seconds': 'time.Second',
    'minutes': 'time.Minute',
    'hours': 'time.Hour',
    'days': 'time.Hour * 24',
  };

  final terms = <String>[];
  for (final argument in creation.argumentList.arguments) {
    final named = argument as NamedExpression;
    final value = (named.expression as IntegerLiteral).value!;
    terms.add('$value * ${goUnit[named.name.label.name]}');
  }
  return terms.join(' + ');
}

/// Value expressions the checker accepts, each emitted as one Go expression.
/// Literals stay untyped Go constants, so `x := 0` / `x := 0.5` / `x := true`
/// infer `int` / `float64` / `bool` exactly as `docs/mapping.md` decides.
String _writeExpression(Expression expression, GoDeps deps) {
  if (expression is IntegerLiteral) {
    // Dart lets an int literal stand for a double (`double d = 2;`); Go
    // would infer `int` from a bare `2`, so keep the float-ness explicit.
    final isDouble = expression.staticType?.isDartCoreDouble ?? false;
    return isDouble ? '${expression.value}.0' : '${expression.value}';
  }
  if (expression is DoubleLiteral) {
    return expression.literal.lexeme;
  }
  if (expression is BooleanLiteral) {
    return expression.value ? 'true' : 'false';
  }
  if (expression is SimpleStringLiteral) {
    return _goStringLiteral(expression.value);
  }
  if (expression is Identifier) {
    final constant = _writeConstantReference(expression, deps);
    if (constant != null) return constant;
    return expression.name;
  }
  if (expression is MethodInvocation) {
    final bound = _writeBoundCall(expression, deps);
    if (bound != null) return bound;
  }
  if (expression is ParenthesizedExpression) {
    return '(${_writeExpression(expression.expression, deps)})';
  }
  if (expression is BinaryExpression) {
    // Comparison (==/!=/</<=/>/>=) and logical (&&/||) operators use the
    // same tokens in Go as in Dart. Recorded in `docs/mapping.md`.
    final left = _writeExpression(expression.leftOperand, deps);
    final right = _writeExpression(expression.rightOperand, deps);
    return '$left ${expression.operator.lexeme} $right';
  }
  if (expression is PrefixExpression && expression.operator.lexeme == '!') {
    return '!${_writeExpression(expression.operand, deps)}';
  }
  throw StateError('unchecked expression: ${expression.runtimeType}');
}

/// A `@GoName` on an `external` top-level or static getter names a Go
/// constant or package-level variable, emitted as the bare (package-
/// qualified) identifier: `red` / `Button.a` → `rt.Red` / `rt.ButtonA`.
/// Recorded in `docs/mapping.md`.
String? _writeConstantReference(Identifier reference, GoDeps deps) {
  final element = reference.element;
  if (element is! GetterElement || !element.isStatic) return null;
  final binding = goBindingOf(element);
  if (binding == null) return null;
  _useImport(binding.import, deps);
  return binding.goName;
}

/// `@GoName` calls map 1:1 onto Go calls: a top-level binding becomes
/// `<goName>(args)` (the name is already package-qualified, e.g.
/// `wio.NewDisplay`), a method binding becomes `<receiver>.<goName>(args)`.
/// The binding library's `@GoImport` is recorded so the import block and,
/// for in-tree runtimes, the `go.mod` `replace` are emitted. Recorded in
/// `docs/mapping.md`.
String? _writeBoundCall(MethodInvocation call, GoDeps deps) {
  final callee = call.methodName.element;
  if (callee is! ExecutableElement) return null;
  final binding = goBindingOf(callee);
  if (binding == null) return null;

  _useImport(binding.import, deps);

  final args = call.argumentList.arguments
      .map((arg) => _writeExpression(arg, deps))
      .join(', ');
  final target = call.target;
  if (target == null) {
    return '${binding.goName}($args)';
  }
  return '${(target as SimpleIdentifier).name}.${binding.goName}($args)';
}

void _useImport(GoImportSpec import, GoDeps deps) {
  deps.imports[import.path] = import.alias;
  final local = import.localModule;
  if (local != null) {
    deps.localModules[local.modulePath] = local;
  }
}

String _goStringLiteral(String content) {
  final escaped = content
      .replaceAll(r'\', r'\\')
      .replaceAll('"', r'\"')
      .replaceAll('\n', r'\n')
      .replaceAll('\t', r'\t');
  return '"$escaped"';
}
