// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	rt "example.com/fake/runtime"
	"time"
)

func main() {
	widget := rt.NewWidget()
	count := 0
	widget.Show(10, 20, "hello")
	rt.Beep(3)
	for {
		count++
		widget.Show(10, 20, "tick")
		rt.Beep(count)
		widget.Hide()
		time.Sleep(250 * time.Millisecond)
	}
}
