// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	rt "example.com/fake/runtime"
	"strconv"
)

func main() {
	_t0 := rt.NewWidget()
	_t0.Show(40, 120, "Hello From Dart !")
	_t0.Hide()
	widget := rt.NewWidget()
	widget.Show(0, 0, "ready")
	widget.Fill(rt.Red)
	level := widget.Level()
	rt.Beep(rt.NewWidget().Level())
	println("level=" + strconv.Itoa(level) + " chained=" + strconv.Itoa(rt.NewWidget().Level()))
}
