// Code generated by dart2tinygo. DO NOT EDIT.
package main

import "strconv"

type Rect struct {
	width  int
	height int
}

func NewRect(width int, height int) *Rect {
	r := &Rect{width: width, height: height}
	if r.width < 0 {
		r.width = 0
	}
	return r
}

func (r *Rect) area() int {
	return r.width * r.height
}

func (r *Rect) grow() {
	r.width++
	r.bumpHeight()
}

func (r *Rect) bumpHeight() {
	r.height += 1
}

func main() {
	r := NewRect(3, 4)
	println(strconv.Itoa(r.area()))
	r.grow()
	println(strconv.Itoa(r.width) + " " + strconv.Itoa(r.height))
}
