// Code generated by dart2tinygo. DO NOT EDIT.
package main

import "strconv"

type Counter struct {
	value int
}

func NewCounter(value int) *Counter {
	return &Counter{value: value}
}

func (c *Counter) inc() {
	c.value++
}

func (c *Counter) addTo(value int) int {
	return c.value + value
}

func main() {
	c := NewCounter(0)
	c.inc()
	c.inc()
	println(strconv.Itoa(c.value))
	println(strconv.Itoa(c.addTo(3)))
	c.value = 10
	c.value += 5
	same := c == c
	println(strconv.FormatBool(same))
}
