// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	rt "example.com/fake/runtime"
	dartrt "github.com/o-ga09/dart2tinygo/packages/dart2tinygo/go"
	"math"
	"strconv"
	"time"
)

func main() {
	widget := rt.NewWidget()
	raw := rt.ReadLevel()
	scale := float64(raw) / 1024.0 * 3.3
	rounded := int(math.Round(scale))
	truncated := int(scale)
	sum := scale + 0.5
	diff := scale - 0.5
	prod := scale * 2.0
	neg := -scale
	x := 1.0
	x += 0.5
	x -= 0.25
	x *= 2.0
	x /= 4.0
	if scale > 3.0 {
		println("scale=" + dartrt.FormatDouble(scale) + " over 3.0")
	}
	widget.Configure(true, scale, "volts")
	println("scale=" + dartrt.FormatDouble(scale) + " sum=" + dartrt.FormatDouble(sum) + " diff=" + dartrt.FormatDouble(diff) + " prod=" + dartrt.FormatDouble(prod) + " neg=" + dartrt.FormatDouble(neg) + " rounded=" + strconv.Itoa(rounded) + " truncated=" + strconv.Itoa(truncated) + " x=" + dartrt.FormatDouble(x) + " volts=" + dartrt.FormatDouble(rt.Voltage()))
	time.Sleep(50 * time.Millisecond)
}
