// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	dartrt "github.com/o-ga09/dart2tinygo/packages/dart2tinygo/go"
	"math"
	"strconv"
)

func main() {
	x := 3.7
	rounded := int(math.Round(x))
	truncated := int(x)
	d := 5
	scaled := float64(d) / 2.0
	println("rounded=" + strconv.Itoa(rounded) + " truncated=" + strconv.Itoa(truncated) + " scaled=" + dartrt.FormatDouble(scaled) + " x=" + dartrt.FormatDouble(x))
}
