// Code generated by dart2tinygo. DO NOT EDIT.
package main

import "strconv"

type Mode int

const (
	ModeOff Mode = iota
	ModeOn
)

var modeNames = [...]string{"off", "on"}

func main() {
	m := ModeOn
	println(modeNames[m])
	println(strconv.Itoa(int(m)))
	switch m {
	case ModeOff:
		println("off")
	case ModeOn:
		println("on")
	}
	if m == ModeOn {
		println("is on")
	}
}
