// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	rt "example.com/fake/runtime"
	"strconv"
	"time"
)

func main() {
	widget := rt.NewWidget()
	button := rt.ButtonA
	count := 0
	level := 2
	threshold := 1.5
	ready := true
	if rt.IsReady() {
		println("ready at boot")
	}
	for {
		if widget.Press(button) {
			count++
			println("pressed " + strconv.Itoa(count))
		} else if widget.Press(rt.ButtonB) {
			println("b pressed")
		} else {
			println("idle")
		}
		if level > 0 && level <= 10 {
			println("in range")
		}
		if !ready || level == 0 {
			println("not ready")
		}
		if rt.Voltage() >= threshold {
			println("ok")
		}
		if level > 0 {
			if level > 5 {
				println("big")
			} else {
				println("small")
			}
		}
		rt.Beep(level)
		time.Sleep(50 * time.Millisecond)
	}
}
