// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	dartrt "github.com/o-ga09/dart2tinygo/packages/dart2tinygo/go"
	"strconv"
)

func main() {
	a := -5
	b := dartrt.Mod(a, 3)
	c := a / 3
	sum := a + b
	diff := a - b
	prod := a * (b + 1)
	neg := -a
	i := 10
	i += 1
	i -= 2
	i *= 3
	i /= 2
	i = dartrt.Mod(i, 4)
	for j := 0; j < 5; j += 2 {
		println(strconv.Itoa(j))
	}
	println(strconv.Itoa(sum) + " " + strconv.Itoa(diff) + " " + strconv.Itoa(prod) + " " + strconv.Itoa(neg) + " " + strconv.Itoa(c) + " " + strconv.Itoa(i))
}
