// Code generated by dart2tinygo. DO NOT EDIT.
package main

import "strconv"

func main() {
	data := []byte{byte(1), byte(2), byte(3)}
	data = append(data, byte(4))
	data[0] = byte(42)
	first := int(data[0])
	n := len(data)
	s := "hello world"
	greeting := s[0:5]
	rest := s[6:]
	combined := greeting + rest
	codes := []byte(s)
	text := string(codes)
	textLen := len(text)
	println("first=" + strconv.Itoa(first) + " n=" + strconv.Itoa(n) + " greeting=" + greeting + " rest=" + rest + " combined=" + combined + " text=" + text + " textLen=" + strconv.Itoa(textLen))
}
