// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	rt "example.com/fake/runtime"
	"strconv"
)

func main() {
	widget := rt.NewWidget()
	data := widget.ReadBytes("/config.txt")
	text := string(data)
	widget.WriteBytes("/log.txt", []byte("hello"))
	println("read " + strconv.Itoa(len(data)) + " bytes: " + text)
}
