// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	rt "example.com/fake/runtime"
	"strconv"
	"time"
)

func main() {
	widget := rt.NewWidget()
	for y := 0; y < 240; y += 20 {
		widget.Show(0, y, "line")
	}
	count := 0
	for count < 10 {
		count++
	}
	sum := 0
	for i := 0; i < 5; i++ {
		if i == 3 {
			break
		}
		if i == 1 {
			continue
		}
		sum += i
	}
	scale := 1.0
	for scale < 2.0 {
		scale *= 1.1
	}
	println("count=" + strconv.Itoa(count) + " sum=" + strconv.Itoa(sum))
	rt.Beep(count)
	time.Sleep(10 * time.Millisecond)
}
