// Code generated by dart2tinygo. DO NOT EDIT.
package main

import (
	"strconv"
	"time"
)

func main() {
	count := 0
	for {
		count++
		println("blink " + strconv.Itoa(count))
		time.Sleep(500 * time.Millisecond)
	}
}
