// Code generated by dart2tinygo. DO NOT EDIT.
package main

func main() {
	mode := 2
	switch mode {
	case 0:
		println("off")
	case 1, 2:
		println("on")
	default:
		println("?")
	}
	name := "b"
	switch name {
	case "a":
		println("first")
	case "b":
		println("second")
	default:
		println("other")
	}
	flag := true
	switch flag {
	case true:
		println("yes")
	case false:
		println("no")
	}
}
