// Code generated by dart2tinygo. DO NOT EDIT.
package main

import "strconv"

func square(x int) int {
	return x * x
}

func blink(times int) {
	i := 0
	for i < times {
		println("blink " + strconv.Itoa(square(i)))
		i++
	}
}

func fib(n int) int {
	if n < 2 {
		return n
	}
	return fib(n-1) + fib(n-2)
}

func log(s string) {
	println(s)
}

func main() {
	blink(3)
	result := fib(6)
	println("fib(6)=" + strconv.Itoa(result))
	log("done")
}
