// Code generated by dart2tinygo. DO NOT EDIT.
package main

import rt "example.com/fake/runtime"

func pressTwice(w *rt.Widget, b rt.Button) {
	w.Press(b)
	w.Press(b)
}

func firstButton() rt.Button {
	return rt.ButtonA
}

func main() {
	widget := rt.NewWidget()
	pressTwice(widget, firstButton())
}
